# Generated by Django 2.1.15 on 2022-04-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('densecID', '0002_dendrites_prod_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dendrites',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
